### PR TITLE
added Robust ICA

### PR DESCRIPTION
**Pull request by csaid**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
This generally looks good to me. A few comments/questions:

(1) Can we make sure that the original source has a coherent license? I searched for its license and found ad hoc text about being free to use. Before we can use this code, we need to confirm that the author doesn't object to using a well-defined open source license like our MIT license or a BSD alternative that can be combined safely with our code.

(2) Can we switch the `deftype` argument to use a Symbol or a Bool?

(3) We'll want to edit this code to work in-place rather than allocating memory. I can do that after the code is merged.

**Comment by csaid** [comment]
Hi John - I'm guessing that the original author, Vicente, does not yet have
a coherent license. Unclear from your email: Do you want him to attach a
license to his own code? Or, easier for him, could he instead just give us
an ok to use an MIT license on our own code that mentions him?

I will switch deftype, push it to my repository, and then submit another
pull request.

Chris

**Comment by johnmyleswhite** [comment]
If he's happy to allow us to use an MIT license for a translation of his code, that's good enough.

This pull request will update automatically once you make your changes.

**Comment by csaid** [comment]
hey john, you may want to chip into the email I just sent to Vicente. Sorry
to drag you into all this.

**Comment by johnmyleswhite** [comment]
Since we spoke with Vicente, let's merge this and then add the notice he requested.

**Pull request merged**
