### PR TITLE
Docs: deprecated NMF, improved docs as proposed in #10

### PR DESCRIPTION
**Pull request by cbecker**
@johnmyleswhite  I just saw that Tim had also proposed changes to the PCA docs, and that NMF was removed ( https://github.com/JuliaStats/DimensionalityReduction.jl/pull/10 ). 

I guess this pull request would close #10, by extending #16

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
We should deprecate everything except PCA (and maybe MDS).

**Comment by cbecker** [comment]
with MDS you mean t-SNE ?

I was thinking of coding LDA at some point, which is pretty simple and very useful.
So in the near future it would be t-SNE, PCA and LDA I guess.

**Comment by cbecker** [comment]
@johnmyleswhite I can take care of deprecating everything except PCA and t-SNE, I just want to make sure that with MDS you meant t-SNE. I can update both code & docs.

**Comment by johnmyleswhite** [comment]
No, I think the t-SNE implementation needs more work. Maybe this package never had MDS in it?

For now, let's just deprecate everything that's not PCA until we have time to work on them.

**Comment by cbecker** [comment]
Ok I will take care of that.

Maybe you meant the Affinity Propagation method in https://github.com/JuliaStats/Clustering.jl when you mentioned MDS.

**Comment by johnmyleswhite** [comment]
No, I mean multidimensional scaling.

**Comment by johnmyleswhite** [comment]
We are, in fact, exporting mds in the current code.

**Comment by cbecker** [comment]
ok so it was just not in the docs, this is also a good chance to add it when I deprecate the rest.

**Comment by johnmyleswhite** [comment]
Let's hold off on adding it until we can confirm that it works correctly.

**Comment by cbecker** [comment]
@johnmyleswhite should be fine now with the deprecations in the docs and code.

**Comment by johnmyleswhite** [comment]
Looks good. If you don't mind, would be nice to squash into one commit.

**Comment by cbecker** [comment]
@johnmyleswhite no problem, done.

**Comment by johnmyleswhite** [comment]
Great. Thanks for doing all this!

**Comment by cbecker** [comment]
@johnmyleswhite no problem. Do you think this is worth a release? I keep pushing for that because then it eases things up for me as well, since I can just do Pkg.update() and assume I have the right version.

**Comment by johnmyleswhite** [comment]
Yeah, definitely ready to release.

**Pull request merged**
