### PR TITLE
Added isomap and diffusion maps algorithms

### PR DESCRIPTION
**Pull request by wildart**
Added isomap and diffusion maps algorithms, adopted from "Matlab Toolbox for Dimensionality Reduction" by Laurens van der Maaten

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
I believe the license for van der Maaten's code is effectively closed source.

**Comment by simonster** [comment]
Well, the license says that modifications can be redistributed but only for non-commercial use, so this code is redistributable, although perhaps it shouldn't be in this package. It may be worth contacting van der Maaten; he was [previously willing](https://groups.google.com/forum/#!topic/julia-users/aBJIcjwqzCM) to license t-SNE under a BSD license.

**Comment by johnmyleswhite** [comment]
It would be great to reach out van der Maaten to ask him to use a BSD license.

Since I didn't say it before, thanks for doing this, @wildart. If we can resolve the licensing issues, this would be really great functionality to offer.

**Comment by wildart** [comment]
It was faster to translate, but if could properly rewrite it. In any case, I'll keep adding some of my manifold learning code.

**Comment by wildart** [comment]
Added LLE, HLLE, LEM, Isomap, Diffmap. They are all written from scratch, so there are no licensing issues.

**Pull request closed without merging**
